spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQATRARmlItMB/xp35dfn/7tIFtyLdwG9KGe5P22Vqm8LwHbBdI2KYxQZgBpkVjHbkUmvVD9qhYRMFoyQ7RYLSa6BF0xSenyRmstlzu8NxSyBHqPidBKZz78SiacoBcvJ/xIf+8cNn0qCDE2GsrG/5YIsU1WVJ2pbGz/moU+An4jP+Abvu9SHJieHT3d/TKUl7ungAFZ/IqrJMRT8+idBxeR4cEB/Ws6Q8Z756pvWdklymLGN91szXI8YDs5BNRBCrsLLFVaaDso45mFoRwIBylQY1Rnm4SvdtzCfoDywYgXGJw8FQhBisYmddtfmDIzDiGJaNDUauButSVcX/u03eZqHjwISl3u8UoJpImnmwLeKr4xJKw3zoEUkEfsHypvZpc='

token:
  expiration_time: 864000000
  secret: '{cipher}AQBefa8plDCaYwPQqe/lkR2llXyF/YBzOLKbSTFoJTXPzziG/iYgbKfN5AZYXQDEpxrq/tDaKMrIuVcPia99WdxAJnq2VZ6b0cv+KuqhjPiagM9LjH+sK3hn/IXpCsgtqMybvI6YskIB1Zabm1zBTvgjbikdTWXym+2AelyeFuOJGdUOW594Ue7b+4adQS/NML62UJqpYs1JRzQB0zybL9S6MyGPnLpL63sv8ASukgZE6LbLTjWEv/YdUInTFNnGUKENFW+C2TmnULJ0iauA6v992Dg3eVV1aDKrabzF0ETgsz1TZWdbMCcuhe2fIbvUdGvz2zxAXHnMtEAKD0l/TkA/y3XEEZueWY3KAOW/PNMUUNSyPIPhDFGtuqZpsU3oA0uFIR5Gp98unfl4/Vi6esknUUookXvywPPKvyDRiFgpQpaaz9xe3ffjTZ1nj5R1LH4LOqnbHlfquQw/uezEExeLulOBSYUG+z4nWojSG0QVVpi53THKjroIiRdRdqJruPZA+NtIk5AsST+fsl0ySg14'

gateway:
  ip: 172.18.0.5

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty: User's orders is empty.
